name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the dockerfile code
      uses: actions/checkout@v3

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
       aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
       aws-region: us-east-1

    - name: Log into ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c8v1l0n9

    - name: Build, tag and push the Docker image
      run: |
        docker build . -t deleonabowu/continuous-serve-image
        docker tag deleonabowu/continuous-serve-image:latest public.ecr.aws/c8v1l0n9/deleonabowu/continuous-serve-image:latest
        docker push public.ecr.aws/c8v1l0n9/deleonabowu/continuous-serve-image:latest

