name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the dockerfile code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t deleonabowu/continuous-serve-image
